# Generated by Django 4.0 on 2022-06-04 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='description',
            new_name='file_name',
        ),
    ]
